package tech.toshitworks.attendo.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFA2003B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD9305C)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF9D3E51)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF9AA9)
val onSecondaryContainerLight = Color(0xFF59081F)
val tertiaryLight = Color(0xFF833C00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBB5800)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF261819)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF261819)
val surfaceVariantLight = Color(0xFFFFD9DD)
val onSurfaceVariantLight = Color(0xFF5A4043)
val outlineLight = Color(0xFF8E6F73)
val outlineVariantLight = Color(0xFFE2BEC1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3D2C2E)
val inverseOnSurfaceLight = Color(0xFFFFECED)
val inversePrimaryLight = Color(0xFFFFB2BC)
val surfaceDimLight = Color(0xFFEFD3D6)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F1)
val surfaceContainerLight = Color(0xFFFFE9EA)
val surfaceContainerHighLight = Color(0xFFFEE2E4)
val surfaceContainerHighestLight = Color(0xFFF8DCDE)

val primaryDark = Color(0xFFFFB2BC)
val onPrimaryDark = Color(0xFF670022)
val primaryContainerDark = Color(0xFFD9305C)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFB2BC)
val onSecondaryDark = Color(0xFF600F25)
val secondaryContainerDark = Color(0xFF731E31)
val onSecondaryContainerDark = Color(0xFFFFC2C9)
val tertiaryDark = Color(0xFFFFB68B)
val onTertiaryDark = Color(0xFF522300)
val tertiaryContainerDark = Color(0xFFBB5800)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1D0F11)
val onBackgroundDark = Color(0xFFF8DCDE)
val surfaceDark = Color(0xFF1D0F11)
val onSurfaceDark = Color(0xFFF8DCDE)
val surfaceVariantDark = Color(0xFF5A4043)
val onSurfaceVariantDark = Color(0xFFE2BEC1)
val outlineDark = Color(0xFFA9898C)
val outlineVariantDark = Color(0xFF5A4043)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF8DCDE)
val inverseOnSurfaceDark = Color(0xFF3D2C2E)
val inversePrimaryDark = Color(0xFFB91247)
val surfaceDimDark = Color(0xFF1D0F11)
val surfaceBrightDark = Color(0xFF463537)
val surfaceContainerLowestDark = Color(0xFF180A0C)
val surfaceContainerLowDark = Color(0xFF261819)
val surfaceContainerDark = Color(0xFF2B1C1D)
val surfaceContainerHighDark = Color(0xFF362628)
val surfaceContainerHighestDark = Color(0xFF423032)






